Assignment: Introduction to Linear Algebra and NumPy
Objective:
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.

Working with NumPy
NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

Task 1:

Import the numpy library and check its version.

In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.5.1


Creating a NumPy Array:
NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

Task 2:

Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].
Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
Generate an array of 10 evenly spaced values between 0 and 5.

In [5]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)


1D Array:
[1 2 3 4 5]


In [7]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ])
print("\n2D Array:")
print(array_2d)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
array_even = np.linspace(0, 5, 10)
print("\n10 Evenly Spaced Values:")
print(array_even)


10 Evenly Spaced Values:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Indexing and Slicing Arrays:
Indexing and slicing allow you to access and modify specific elements of an array.

Task 3:

Access the element in the second row, third column of the 2D array you created above.
Slice the first two rows and the first two columns from the same array.
Modify the value in the last row and first column to 100.

In [9]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [10]:
print("Element:", array_2d[1, 2])

Element: 6


In [11]:
print("Sliced Array:")
print(array_2d[0:2, 0:2])

Sliced Array:
[[1 2]
 [4 5]]


In [13]:
array_2d[2, 0] = 100

print("Modified Array:")
print(array_2d)

Modified Array:
[[  1   2   3]
 [  4   5   6]
 [100   8   9]]


Properties and Methods of NumPy Arrays
NumPy arrays have several useful properties and methods.

Task 4:

Find the shape, size, and data type of the 2D array.
Change the 1D array into a 2D array of shape (5,1).
Flatten a multi-dimensional array back into a 1D array.

In [14]:
array_1d = np.array([1, 2, 3, 4, 5])

In [15]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [17]:
print("Shape:", array_2d.shape)

Shape: (3, 3)


In [18]:
print("Size:", array_2d.size)

Size: 9


In [19]:
print("Data Type:", array_2d.dtype)

Data Type: int64


In [20]:
array_2d_new = array_1d.reshape(5, 1)

In [21]:
print("\n2D Array (5,1):")


2D Array (5,1):


In [22]:
print(array_2d_new)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [23]:
flattened_array = array_2d.flatten()

In [24]:
print("\nFlattened Array:")


Flattened Array:


In [25]:
print(flattened_array)

[1 2 3 4 5 6 7 8 9]


Operations on NumPy Arrays
Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

Task 5:

Add 5 to every element in the 1D array.
Multiply the 2D array by 3.
Perform matrix multiplication between the following two arrays:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [26]:
array_1d = np.array([1, 2, 3, 4, 5])

In [27]:
result_1 = array_1d + 5
print("Add 5:", result_1)

Add 5: [ 6  7  8  9 10]


In [28]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [29]:
result_2 = array_2d * 3
print("\nMultiply by 3:")
print(result_2)


Multiply by 3:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [30]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [31]:
result_3 = np.matmul(A, B)

In [32]:
print("\nMatrix Multiplication:")
print(result_3)


Matrix Multiplication:
[[19 22]
 [43 50]]


Understanding Broadcasting
Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

Task 6:

Create a 3x3 matrix of ones and a 1D array of length 3.
Add the 1D array to each row of the matrix using broadcasting.

In [33]:
matrix = np.ones((3, 3))

In [34]:
array = np.array([1, 2, 3])

In [35]:
result = matrix + array

In [36]:
print("Matrix of Ones:")
print(matrix)

Matrix of Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
print("\n1D Array:")
print(array)



1D Array:
[1 2 3]


In [38]:
print("\nResult:")
print(result)


Result:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
