In [2]:
import numpy as np

a = np.random.randint(10, 50, size =  (5, 2, 3), dtype = "int16")

In [3]:
a.shape

(5, 2, 3)

In [4]:
a.ndim

3

In [5]:
a.dtype

dtype('int16')

In [6]:
a.T

array([[[10, 16, 14, 45, 27],
        [42, 35, 20, 29, 45]],

       [[18, 49, 13, 44, 43],
        [30, 17, 10, 34, 18]],

       [[31, 36, 29, 48, 36],
        [31, 40, 15, 22, 34]]], dtype=int16)

In [7]:
a.size

30

In [12]:
a = np.random.randint(10, 50, size =  (5, 4), dtype = "int16")
a

array([[36, 28, 26, 36],
       [30, 14, 20, 43],
       [37, 24, 20, 48],
       [21, 46, 42, 41],
       [41, 34, 33, 15]], dtype=int16)

In [14]:
b = a.reshape(2, 5, 2)
b

array([[[36, 28],
        [26, 36],
        [30, 14],
        [20, 43],
        [37, 24]],

       [[20, 48],
        [21, 46],
        [42, 41],
        [41, 34],
        [33, 15]]], dtype=int16)

In [15]:
a.reshape(4, -1)

array([[36, 28, 26, 36, 30],
       [14, 20, 43, 37, 24],
       [20, 48, 21, 46, 42],
       [41, 41, 34, 33, 15]], dtype=int16)

In [16]:
a.flatten()

array([36, 28, 26, 36, 30, 14, 20, 43, 37, 24, 20, 48, 21, 46, 42, 41, 41,
       34, 33, 15], dtype=int16)

In [17]:
a.sum()

np.int64(635)

0 -> column wise -> vertical 

1 -> row wise -> horizontal

In [18]:
a.sum(axis = 0)

array([165, 146, 141, 183])

In [19]:
a.sum(axis = 1)

array([126, 107, 129, 150, 123])

In [22]:
a.trace()  #diagonal sum

np.int64(111)

In [23]:
a.cumsum()

array([ 36,  64,  90, 126, 156, 170, 190, 233, 270, 294, 314, 362, 383,
       429, 471, 512, 553, 587, 620, 635])

In [24]:
a.cumsum(axis = 1)

array([[ 36,  64,  90, 126],
       [ 30,  44,  64, 107],
       [ 37,  61,  81, 129],
       [ 21,  67, 109, 150],
       [ 41,  75, 108, 123]])

In [25]:
a.prod()

np.int64(-7581503844413079552)

In [26]:
a.prod(dtype = float)

np.float64(3.334621665652619e+29)

In [27]:
a

array([[36, 28, 26, 36],
       [30, 14, 20, 43],
       [37, 24, 20, 48],
       [21, 46, 42, 41],
       [41, 34, 33, 15]], dtype=int16)

In [28]:
a.argmax(axis=0)

array([4, 3, 3, 2])

In [29]:
a.argmin(axis=1)

array([2, 1, 2, 0, 3])

In [30]:
a.clip(min = 20, max = 40)

array([[36, 28, 26, 36],
       [30, 20, 20, 40],
       [37, 24, 20, 40],
       [21, 40, 40, 40],
       [40, 34, 33, 20]], dtype=int16)

In [31]:
# concat and joining

In [33]:
arr1 = np.random.randint(1, 100, size =  (3, 3))
arr2 = np.random.randint(1, 100, size =  (3, 3))    

In [34]:
arr1, arr2

(array([[53, 36,  7],
        [17, 84, 38],
        [29, 86, 80]]),
 array([[44, 12, 20],
        [32, 10, 58],
        [19, 98, 13]]))

In [35]:
np.concatenate((arr1, arr2))

array([[53, 36,  7],
       [17, 84, 38],
       [29, 86, 80],
       [44, 12, 20],
       [32, 10, 58],
       [19, 98, 13]])

In [ ]:
np.concatenate((arr1, arr2), axis = 0) # vstack

array([[53, 36,  7],
       [17, 84, 38],
       [29, 86, 80],
       [44, 12, 20],
       [32, 10, 58],
       [19, 98, 13]])

In [39]:
np.vstack((arr1, arr2))

array([[53, 36,  7],
       [17, 84, 38],
       [29, 86, 80],
       [44, 12, 20],
       [32, 10, 58],
       [19, 98, 13]])

In [ ]:
np.concatenate((arr1, arr2), axis = 1) # hstack

array([[53, 36,  7, 44, 12, 20],
       [17, 84, 38, 32, 10, 58],
       [29, 86, 80, 19, 98, 13]])

In [40]:
np.hstack((arr1, arr2))

array([[53, 36,  7, 44, 12, 20],
       [17, 84, 38, 32, 10, 58],
       [29, 86, 80, 19, 98, 13]])