In [171]:
import numpy as np

In [172]:
np.__version__

'2.5.1'

creating numpy array

In [173]:
list1 = [1, 2, 3, 4, 5]

array1 = np.array(list1)

In [174]:
array1

array([1, 2, 3, 4, 5])

In [175]:
array1.ndim

1

In [176]:
array1.shape

(5,)

In [177]:
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array2 = np.array(list2)

In [178]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [179]:
array2.ndim

2

In [180]:
array2.shape

(3, 3)

In [181]:
list3 = [
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],[
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
]

array3 = np.array(list3)

In [182]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [183]:
array3.ndim

3

In [184]:
array3.shape

(2, 3, 3)

In [185]:
np.zeros(shape = (2, 3, 4), dtype = "int")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [186]:
np.ones(shape = (5,3,6,6), dtype = "int")

array([[[[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
  

In [187]:
np.full(shape = (3,4), fill_value = 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [188]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [189]:
np.linspace(0, 30, num = 5)

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [190]:
np.linspace((0, 2), (30, 60), num = 5)

array([[ 0. ,  2. ],
       [ 7.5, 16.5],
       [15. , 31. ],
       [22.5, 45.5],
       [30. , 60. ]])

In [191]:
np.linspace((0, 1, 2), (30, 20, 60), num = 5)

array([[ 0.  ,  1.  ,  2.  ],
       [ 7.5 ,  5.75, 16.5 ],
       [15.  , 10.5 , 31.  ],
       [22.5 , 15.25, 45.5 ],
       [30.  , 20.  , 60.  ]])

In [192]:
np.linspace((0, 1, 2), (30, 20, 60), num = 5, axis = 1)

array([[ 0.  ,  7.5 , 15.  , 22.5 , 30.  ],
       [ 1.  ,  5.75, 10.5 , 15.25, 20.  ],
       [ 2.  , 16.5 , 31.  , 45.5 , 60.  ]])

In [193]:
np.linspace((0, 1, 2), (30, 20, 60), num = 5, axis = 0)

array([[ 0.  ,  1.  ,  2.  ],
       [ 7.5 ,  5.75, 16.5 ],
       [15.  , 10.5 , 31.  ],
       [22.5 , 15.25, 45.5 ],
       [30.  , 20.  , 60.  ]])

In [194]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [195]:
np.random.randint(0, 50, size = (3, 2, 4))

array([[[ 8, 15, 40, 30],
        [19, 33, 18, 34]],

       [[ 2, 14, 14, 43],
        [11, 14, 47, 23]],

       [[34,  4, 26, 39],
        [29, 26, 26, 35]]])

elementwise operations

In [196]:
import numpy as np

In [197]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.random.randint(1, 40, size=(2, 2))
c = np.random.randint(0, 60, size=(2, 2), dtype="int")

In [198]:
a, b, c

(array([[1, 2],
        [3, 4]]),
 array([[22, 39],
        [ 2, 36]]),
 array([[39, 35],
        [10, 51]]))

arithmetic operations 

In [199]:
np.add(a, b)

array([[23, 41],
       [ 5, 40]])

In [200]:
np.pow(a, 2)

array([[ 1,  4],
       [ 9, 16]])

In [201]:
quo, rem = np.divmod(a, b)
rem

array([[1, 2],
       [1, 4]])

In [202]:
np.negative(a)

array([[-1, -2],
       [-3, -4]])

In [203]:
np.positive(a)

array([[1, 2],
       [3, 4]])

trignometric

In [204]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [205]:
cot = np.reciprocal(np.tan(b))
cot

array([[112.97321036,   0.27665927],
       [ -0.45765755,   0.12902442]])

rounding operations 

In [206]:
np.round(cot, 2)

array([[112.97,   0.28],
       [ -0.46,   0.13]])

In [207]:
np.floor(cot)

array([[112.,   0.],
       [ -1.,   0.]])

In [208]:
np.ceil(cot)

array([[113.,   1.],
       [ -0.,   1.]])

matrix operations

In [209]:
a

array([[1, 2],
       [3, 4]])

In [210]:
c

array([[39, 35],
       [10, 51]])

In [211]:
b

array([[22, 39],
       [ 2, 36]])

In [212]:
bT = np.transpose(b)
bT

array([[22,  2],
       [39, 36]])

In [213]:
np.dot(a, b)

array([[ 26, 111],
       [ 74, 261]])

In [214]:
a.dot(b)

array([[ 26, 111],
       [ 74, 261]])

In [215]:
a @ bT

array([[100,  74],
       [222, 150]])

In [216]:
d_sum = np.trace(a)
print(d_sum)

5


In [217]:
np.linalg.matrix_rank(a)

np.int64(2)

In [218]:
b = np.random.randint(1, 40, size=(2, 2))

det_b = np.linalg.det(b)
det_b

np.float64(1232.9999999999998)

In [219]:
inv_b = np.linalg.inv(b)
inv_b

array([[ 0.03000811, -0.02838605],
       [-0.00486618,  0.03163017]])

solve equation : 4x + 2y = 8 , 5x + 3y = 9

In [221]:
A = np.array([[4,2], [5, 3]])
B = np.array([[8], [9]])

In [222]:
A_inv = np.linalg.inv(A)

In [225]:
x = np.dot(A_inv, B)

In [226]:
x

array([[ 3.],
       [-2.]])

In [227]:
# array broadcasting
A

array([[4, 2],
       [5, 3]])

In [228]:
B

array([[8],
       [9]])

In [229]:
A + B

array([[12, 10],
       [14, 12]])