In [1]:
import numpy as np

In [2]:
np.__version__

'2.5.1'

creating numpy array

In [3]:
list1 = [1, 2, 3, 4, 5]

array1 = np.array(list1)

In [4]:
array1

array([1, 2, 3, 4, 5])

In [6]:
array1.ndim

1

In [5]:
array1.shape

(5,)

In [7]:
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array2 = np.array(list2)

In [8]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
array2.ndim

2

In [11]:
array2.shape

(3, 3)

In [13]:
list3 = [
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],[
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
]

array3 = np.array(list3)

In [14]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
array3.ndim

3

In [16]:
array3.shape

(2, 3, 3)

In [21]:
np.zeros(shape = (2, 3, 4), dtype = "int")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [22]:
np.ones(shape = (5,3,6,6), dtype = "int")

array([[[[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
  

In [24]:
np.full(shape = (3,4), fill_value = 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [25]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.linspace(0, 30, num = 5)

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [28]:
np.linspace((0, 2), (30, 60), num = 5)

array([[ 0. ,  2. ],
       [ 7.5, 16.5],
       [15. , 31. ],
       [22.5, 45.5],
       [30. , 60. ]])

In [36]:
np.linspace((0, 1, 2), (30, 20, 60), num = 5)

array([[ 0.  ,  1.  ,  2.  ],
       [ 7.5 ,  5.75, 16.5 ],
       [15.  , 10.5 , 31.  ],
       [22.5 , 15.25, 45.5 ],
       [30.  , 20.  , 60.  ]])

In [35]:
np.linspace((0, 1, 2), (30, 20, 60), num = 5, axis = 1)

array([[ 0.  ,  7.5 , 15.  , 22.5 , 30.  ],
       [ 1.  ,  5.75, 10.5 , 15.25, 20.  ],
       [ 2.  , 16.5 , 31.  , 45.5 , 60.  ]])

In [37]:
np.linspace((0, 1, 2), (30, 20, 60), num = 5, axis = 0)

array([[ 0.  ,  1.  ,  2.  ],
       [ 7.5 ,  5.75, 16.5 ],
       [15.  , 10.5 , 31.  ],
       [22.5 , 15.25, 45.5 ],
       [30.  , 20.  , 60.  ]])

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.random.randint(0, 50, size = (3, 2, 4))

array([[[26, 28,  3, 13],
        [36, 19, 16, 32]],

       [[16, 30, 34, 48],
        [34, 36, 11,  9]],

       [[45,  9, 20, 36],
        [12, 40, 17, 43]]])